# Generated by Django 5.2 on 2025-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=255, unique=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('pii', models.CharField(blank=True, max_length=255, null=True)),
                ('pubmed_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('subtypeDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('afid', models.CharField(blank=True, max_length=255, null=True)),
                ('affilname', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation_city', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation_country', models.CharField(blank=True, max_length=255, null=True)),
                ('author_count', models.IntegerField(blank=True, null=True)),
                ('author_names', models.TextField(blank=True, null=True)),
                ('author_ids', models.TextField(blank=True, null=True)),
                ('author_afids', models.TextField(blank=True, null=True)),
                ('coverDate', models.DateField(blank=True, null=True)),
                ('coverDisplayDate', models.CharField(blank=True, max_length=50, null=True)),
                ('publicationName', models.CharField(blank=True, max_length=255, null=True)),
                ('issn', models.CharField(blank=True, max_length=20, null=True)),
                ('source_id', models.CharField(blank=True, max_length=20, null=True)),
                ('eIssn', models.CharField(blank=True, max_length=20, null=True)),
                ('aggregationType', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('issueIdentifier', models.CharField(blank=True, max_length=20, null=True)),
                ('article_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pageRange', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('authkeywords', models.TextField(blank=True, null=True)),
                ('citedby_count', models.IntegerField(blank=True, null=True)),
                ('openaccess', models.BooleanField(default=False)),
                ('freetoread', models.CharField(blank=True, max_length=50, null=True)),
                ('freetoreadLabel', models.CharField(blank=True, max_length=50, null=True)),
                ('fund_acr', models.TextField(blank=True, null=True)),
                ('fund_no', models.TextField(blank=True, null=True)),
                ('fund_sponsor', models.TextField(blank=True, null=True)),
                ('ref_docs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
